title: Jain Basil's Blog
author: jainbasil
description: >- # this means to ignore newlines until "baseurl:"
  Director of Engineering at Zoko (YC 2021).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jainbasil.in" # the base hostname & protocol for your site, e.g. http://example.com
lang: en-GB
timezone: UTC

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false

# Build settings
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - README.md

# Outputting
permalink: /:year/:month/:day/:title/

# Markdown settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# jekyll-paginate
paginate_path: /posts/:num/
paginate: 5
