title: Jain Basil's Blog
author:
  name: Jain Basil Aliyas
  email: jainbasil@gmail.com
description: >-
  Hi! I am a backend developer passionate about building highly scalable and data-intensive cloud applications, open-source software etc. I occasionally write here about computers and programming, book reviews, travelogues and photographs. Feel free to contact me over <a href="mailto:jainbasil+blog@gmail.com">email</a> and <a href="https://www.linkedin.com/in/jainbasil">LinkedIn</a>.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-calculus-theme
